package main

import (
	"image/color"
	"log"
	"math"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/vector"
)

const (
	screenWidth  = 800
	screenHeight = 600
)

// WaveParticle tracks an individual wave burst generated by the boat
type WaveParticle struct {
	X, Y      float64 // Origin position
	Radius    float64 // Current expanding radius
	Amplitude float64 // Wave height/strength (fades over time)
	Speed     float64 // Expansion velocity
	Life      float64 // Remaining lifespan (1.0 down to 0.0)
}

type Boat struct {
	X, Y  float64
	Angle float64 // In radians
	Speed float64
}

type Game struct {
	boat       Boat
	particles  []*WaveParticle
	heightmap  *ebiten.Image // Offscreen canvas to accumulate wave data
	spawnTimer int
}

func NewGame() *Game {
	return &Game{
		boat:      Boat{X: screenWidth / 2, Y: screenHeight / 2, Angle: 0, Speed: 0},
		heightmap: ebiten.NewImage(screenWidth, screenHeight),
	}
}

func (g *Game) Update() error {
	// 1. Boat Movement Input
	if ebiten.IsKeyPressed(ebiten.KeyLeft) || ebiten.IsKeyPressed(ebiten.KeyA) {
		g.boat.Angle -= 0.05
	}
	if ebiten.IsKeyPressed(ebiten.KeyRight) || ebiten.IsKeyPressed(ebiten.KeyD) {
		g.boat.Angle += 0.05
	}
	if ebiten.IsKeyPressed(ebiten.KeyUp) || ebiten.IsKeyPressed(ebiten.KeyW) {
		g.boat.Speed = 3.5
	} else {
		g.boat.Speed *= 0.95 // Friction decelerates the boat
	}

	// Move the boat based on velocity and angle
	g.boat.X += math.Cos(g.boat.Angle) * g.boat.Speed
	g.boat.Y += math.Sin(g.boat.Angle) * g.boat.Speed

	// 2. Spawn Wave Particles if moving
	if g.boat.Speed > 0.5 {
		g.spawnTimer++
		if g.spawnTimer >= 4 { // Emit every 4 frames
			g.spawnTimer = 0
			// Calculate the back/stern of the boat to emit waves
			sternX := g.boat.X - math.Cos(g.boat.Angle)*15
			sternY := g.boat.Y - math.Sin(g.boat.Angle)*15

			g.particles = append(g.particles, &WaveParticle{
				X:         sternX,
				Y:         sternY,
				Radius:    2.0,
				Amplitude: g.boat.Speed * 25.0, // Speed determines wave intensity
				Speed:     1.5,                 // Spread velocity
				Life:      1.0,
			})
		}
	}

	// 3. Update Wave Particles (Advection & Decay)
	activeParticles := g.particles[:0]
	for _, p := range g.particles {
		p.Radius += p.Speed
		p.Life -= 0.015 // Decay rate per frame

		if p.Life > 0 {
			activeParticles = append(activeParticles, p)
		}
	}
	g.particles = activeParticles

	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	// 1. Clear screens
	screen.Fill(color.RGBA{10, 50, 110, 255}) // Deep blue ocean base
	g.heightmap.Clear()                       // Clear the wave canvas

	// 2. Synthesis: Draw Wave Particles into the canvas
	// We draw expanding, fading rings using ebiten vector graphics
	for _, p := range g.particles {
		alpha := uint8(p.Life * p.Amplitude)
		if alpha > 255 {
			alpha = 255
		}

		// Draw a stroke ring representing the wave crest
		vector.StrokeCircle(
			g.heightmap,
			float32(p.X),
			float32(p.Y),
			float32(p.Radius),
			3.0, // Thickness of the wave ripple crest
			color.RGBA{255, 255, 255, alpha},
			true,
		)
	}

	// 3. Draw the waves onto the screen
	// In a complete game, you would pass 'g.heightmap' to a fragment shader
	// to distort the water texture. Here, we composite it directly to see the wave fields.
	opts := &ebiten.DrawImageOptions{}
	opts.Blend = ebiten.BlendLighter // Blend ripples together cleanly
	screen.DrawImage(g.heightmap, opts)

	// 4. Draw the Boat (Triangle representation)
	boatOpts := &ebiten.DrawImageOptions{}
	// Center rotation origin
	boatOpts.GeoM.Translate(-10, -5)
	boatOpts.GeoM.Rotate(g.boat.Angle)
	boatOpts.GeoM.Translate(g.boat.X, g.boat.Y)

	// Simple procedural boat sprite
	boatImg := ebiten.NewImage(20, 10)
	var path vector.Path
	path.MoveTo(0, 0)
	path.LineTo(15, 0)
	path.LineTo(20, 5)
	path.LineTo(15, 10)
	path.LineTo(0, 10)
	path.Close()
	vertices, indices := path.AppendVerticesAndIndicesForFilling(nil, nil)
	emptyImage := ebiten.NewImage(3, 3)
	emptyImage.Fill(color.White)
	
	// Set color on vertices
	clr := color.RGBA{180, 100, 50, 255}
	rf := float32(clr.R) / 255.0
	gf := float32(clr.G) / 255.0
	bf := float32(clr.B) / 255.0
	af := float32(clr.A) / 255.0
	for idx := range vertices {
		vertices[idx].ColorR = rf
		vertices[idx].ColorG = gf
		vertices[idx].ColorB = bf
		vertices[idx].ColorA = af
	}
	boatImg.DrawTriangles(vertices, indices, emptyImage, nil)
	screen.DrawImage(boatImg, boatOpts)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return screenWidth, screenHeight
}

func main() {
	ebiten.SetWindowSize(screenWidth, screenHeight)
	ebiten.SetWindowTitle("2D Boat Wave Particle System")
	if err := ebiten.RunGame(NewGame()); err != nil {
		log.Fatal(err)
	}
}
